export const systemDesignConceptSeeds = [
    {
        slug: 'latency-throughput-availability',
        title: 'Latency, Throughput, and Availability',
        category: 'fundamentals',
        level: 'beginner',
        summary: 'Understand the three numbers every design discussion keeps coming back to.',
        analogy: 'A restaurant needs fast service for one customer, capacity for the dinner rush, and backup plans when one chef is unavailable.',
        explanation: 'Latency is how long one request waits. Throughput is how many requests the system handles per second. Availability is the percentage of time the system can serve users. Strong designs name which one matters most for the product.',
        diagram: ['Client request', 'Application service', 'Database/cache', 'Response'],
        tradeoffs: [
            { optionA: 'Lower latency', optionB: 'Higher durability', decisionRule: 'Use caching when slightly stale data is acceptable.' },
            { optionA: 'Higher availability', optionB: 'Strong consistency', decisionRule: 'Use replicas and eventual consistency when uptime matters more than instant global agreement.' },
        ],
        quiz: [
            {
                question: 'A feed page feels slow for one user. Which metric is most directly affected?',
                options: ['Latency', 'Throughput', 'Storage'],
                correctIndex: 0,
                explanation: 'Latency measures the time for one request to complete.',
            },
        ],
        drill: {
            prompt: 'Pick one app you use daily and estimate which metric its users notice first.',
            checklist: ['Name the user action', 'Name the primary metric', 'Explain the tradeoff'],
        },
        order: 1,
    },
    {
        slug: 'load-balancer-cache-database',
        title: 'Load Balancer, Cache, and Database',
        category: 'components',
        level: 'beginner',
        summary: 'Learn the first three building blocks behind most scalable web systems.',
        analogy: 'A receptionist routes people, a sticky note answers repeated questions quickly, and the filing cabinet stores the official record.',
        explanation: 'A load balancer spreads traffic across servers. A cache stores hot reads close to the application. A database keeps durable source-of-truth data. Most beginner designs become clearer when these roles are separated.',
        diagram: ['Users', 'Load balancer', 'App servers', 'Cache', 'Database'],
        tradeoffs: [
            { optionA: 'Cache reads', optionB: 'Read database every time', decisionRule: 'Cache when reads repeat often and freshness tolerance exists.' },
            { optionA: 'Scale app servers', optionB: 'Scale database first', decisionRule: 'Scale stateless app servers before touching harder database scaling.' },
        ],
        quiz: [
            {
                question: 'Which component usually owns the durable source of truth?',
                options: ['Load balancer', 'Cache', 'Database'],
                correctIndex: 2,
                explanation: 'Caches may be stale or temporary; databases hold durable state.',
            },
        ],
        drill: {
            prompt: 'Sketch a read-heavy product page using these three components.',
            checklist: ['Route request', 'Read cache first', 'Fallback to database', 'Update cache on miss'],
        },
        order: 2,
    },
    {
        slug: 'queues-and-async-work',
        title: 'Queues and Async Work',
        category: 'components',
        level: 'intermediate',
        summary: 'Use queues to protect user-facing requests from slow background work.',
        analogy: 'A front desk accepts your form quickly, then a back office processes it in order.',
        explanation: 'Queues decouple producers from workers. They help absorb spikes, retry failed work, and keep request latency low for tasks like emails, thumbnails, notifications, and analytics.',
        diagram: ['API service', 'Message queue', 'Worker pool', 'External service/storage'],
        tradeoffs: [
            { optionA: 'Async queue', optionB: 'Synchronous request', decisionRule: 'Queue work that does not need to finish before responding to the user.' },
            { optionA: 'At-least-once delivery', optionB: 'Exactly-once behavior', decisionRule: 'Design idempotent workers because retries can happen.' },
        ],
        quiz: [
            {
                question: 'Which task is a good queue candidate?',
                options: ['Password validation before login', 'Sending a welcome email', 'Checking required form fields'],
                correctIndex: 1,
                explanation: 'The welcome email can happen after the response, so it can be queued.',
            },
        ],
        drill: {
            prompt: 'Design async image thumbnail generation for uploaded photos.',
            checklist: ['Accept upload quickly', 'Publish job', 'Worker processes image', 'Store result', 'Handle retry'],
        },
        order: 3,
    },
    {
        slug: 'sql-nosql-sharding',
        title: 'SQL, NoSQL, and Sharding',
        category: 'tradeoffs',
        level: 'intermediate',
        summary: 'Choose storage based on access pattern, consistency needs, and scale shape.',
        analogy: 'A spreadsheet is great for structured joins; labeled boxes are better when every item has a different shape and must be fetched quickly by key.',
        explanation: 'SQL is strong for relational data, joins, and transactions. NoSQL often favors flexible schema or high-scale key access. Sharding splits data across machines when one database cannot carry the load.',
        diagram: ['Application', 'Router/shard key', 'Shard A', 'Shard B', 'Replica'],
        tradeoffs: [
            { optionA: 'SQL', optionB: 'NoSQL', decisionRule: 'Use SQL when relationships and transactions dominate.' },
            { optionA: 'Shard by user id', optionB: 'Shard by time', decisionRule: 'Choose a shard key that spreads load and matches common queries.' },
        ],
        quiz: [
            {
                question: 'What is the biggest risk of a poor shard key?',
                options: ['Hot partitions', 'More CSS', 'Faster joins'],
                correctIndex: 0,
                explanation: 'A bad shard key can send too much traffic to one shard.',
            },
        ],
        drill: {
            prompt: 'Pick a shard key for a chat app and explain one risk.',
            checklist: ['Identify primary query', 'Choose shard key', 'Discuss hot rooms/users', 'Mention mitigation'],
        },
        order: 4,
    },
    {
        slug: 'design-url-shortener',
        title: 'Case Study: URL Shortener',
        category: 'case_studies',
        level: 'interview',
        summary: 'Practice a full beginner-friendly system design prompt with clear tradeoffs.',
        analogy: 'A cloakroom gives a tiny token for a large bag and later retrieves the bag using that token.',
        explanation: 'A URL shortener maps a short code to a long URL. The core design covers code generation, redirect latency, storage, cache, analytics, and abuse controls.',
        diagram: ['Client', 'API service', 'Code generator', 'Database', 'Cache', 'Analytics queue'],
        tradeoffs: [
            { optionA: 'Random code', optionB: 'Counter-based code', decisionRule: 'Use random codes for simpler distributed generation; handle collisions.' },
            { optionA: 'Cache redirects', optionB: 'Always read database', decisionRule: 'Cache hot short codes because redirects are read-heavy.' },
        ],
        quiz: [
            {
                question: 'Why is cache useful in a URL shortener?',
                options: ['Redirects are read-heavy', 'It replaces the database permanently', 'It generates CSS'],
                correctIndex: 0,
                explanation: 'Popular short links may be read many times, so cache reduces latency and database load.',
            },
        ],
        drill: {
            prompt: 'Design a URL shortener for 100M links and read-heavy redirects.',
            checklist: ['Functional requirements', 'QPS estimate', 'Short code strategy', 'Storage', 'Cache', 'Analytics'],
        },
        order: 5,
    },
]

export const systemDesignPromptSeeds = [
    {
        slug: 'url-shortener',
        title: 'Design a URL Shortener',
        difficulty: 'Easy',
        scenario: 'Design a service that creates short links and redirects users to long URLs with low latency.',
        requirements: ['Create short URL', 'Redirect short URL', 'Track basic click analytics', 'Handle custom aliases optionally'],
        scaleAssumptions: ['100M stored URLs', 'Read-heavy traffic', 'Popular links can spike'],
        expectedComponents: ['API service', 'Code generator', 'Database', 'Cache', 'Analytics queue'],
        tradeoffFocus: ['Code generation strategy', 'Cache freshness', 'Collision handling'],
        followUps: ['How do you prevent abuse?', 'How do you expire links?', 'How do you support custom aliases?'],
        order: 1,
    },
    {
        slug: 'chat-app',
        title: 'Design a Chat App',
        difficulty: 'Medium',
        scenario: 'Design one-to-one and small-group messaging with online delivery and message history.',
        requirements: ['Send messages', 'Receive messages in near real time', 'Store history', 'Show delivery status'],
        scaleAssumptions: ['Millions of users', 'Many idle connections', 'Messages must be durable'],
        expectedComponents: ['Gateway/WebSocket service', 'Message service', 'Queue', 'Database', 'Presence store'],
        tradeoffFocus: ['WebSocket vs polling', 'Ordering', 'Offline delivery'],
        followUps: ['How do you handle huge groups?', 'How do you support search?', 'How do you retry failed sends?'],
        order: 2,
    },
    {
        slug: 'rate-limiter',
        title: 'Design a Rate Limiter',
        difficulty: 'Medium',
        scenario: 'Design a service that limits requests per user or API key to protect backend systems.',
        requirements: ['Enforce request limits', 'Return retry guidance', 'Support distributed servers'],
        scaleAssumptions: ['High QPS', 'Multiple regions optional', 'Low latency decision needed'],
        expectedComponents: ['API gateway', 'Counter store', 'Rules config', 'Metrics'],
        tradeoffFocus: ['Token bucket vs fixed window', 'Redis counters', 'Consistency under distribution'],
        followUps: ['How do you avoid hot keys?', 'How do you handle burst traffic?', 'How do you test correctness?'],
        order: 3,
    },
]
