export const systemDesignConceptSeeds = [
    {
        slug: 'latency-throughput-availability',
        title: 'Latency, Throughput, and Availability',
        category: 'fundamentals',
        level: 'beginner',
        summary: 'Understand the three numbers every design discussion keeps coming back to.',
        analogy: 'A restaurant needs fast service for one customer, capacity for the dinner rush, and backup plans when one chef is unavailable.',
        explanation: 'Latency is how long one request waits. Throughput is how many requests the system handles per second. Availability is the percentage of time the system can serve users. Strong designs name which one matters most for the product.',
        diagram: ['Client request', 'Application service', 'Database/cache', 'Response'],
        tradeoffs: [
            { optionA: 'Lower latency', optionB: 'Higher durability', decisionRule: 'Use caching when slightly stale data is acceptable.' },
            { optionA: 'Higher availability', optionB: 'Strong consistency', decisionRule: 'Use replicas and eventual consistency when uptime matters more than instant global agreement.' },
        ],
        quiz: [
            {
                question: 'A feed page feels slow for one user. Which metric is most directly affected?',
                options: ['Latency', 'Throughput', 'Storage'],
                correctIndex: 0,
                explanation: 'Latency measures the time for one request to complete.',
            },
        ],
        drill: {
            prompt: 'Pick one app you use daily and estimate which metric its users notice first.',
            checklist: ['Name the user action', 'Name the primary metric', 'Explain the tradeoff'],
        },
        order: 1,
    },
    {
        slug: 'dns-cdn',
        title: 'DNS and CDN (Content Delivery)',
        category: 'fundamentals',
        level: 'beginner',
        summary: 'Map user-friendly domain names and cache static content near the user.',
        analogy: 'A phonebook maps names to numbers; local distribution warehouses store hot items nearby to speed up delivery.',
        explanation: 'DNS resolves text domain names to numeric IP addresses. CDNs serve static and dynamic content from Edge locations closer to users, avoiding a round-trip to the origin server.',
        diagram: ['Client DNS request', 'DNS resolver', 'CDN Edge Server', 'Origin Server'],
        tradeoffs: [
            { optionA: 'Short TTL (Time To Live)', optionB: 'Long TTL', decisionRule: 'Use short TTL when DNS records or static assets change frequently.' },
            { optionA: 'Edge Caching', optionB: 'Origin Fetching', decisionRule: 'Cache static assets on the edge; route dynamic or transactional reads to the origin.' },
        ],
        quiz: [
            {
                question: 'Which component is responsible for resolving a domain name like google.com to an IP address?',
                options: ['CDN', 'Load Balancer', 'DNS'],
                correctIndex: 2,
                explanation: 'The Domain Name System (DNS) performs IP address lookup for domains.',
            },
        ],
        drill: {
            prompt: 'Explain the difference between a cache hit and a cache miss in a CDN.',
            checklist: ['Explain Cache Hit', 'Explain Cache Miss', 'Describe fallback to Origin Server'],
        },
        order: 2,
    },
    {
        slug: 'load-balancer-cache-database',
        title: 'Load Balancer, Cache, and Database',
        category: 'components',
        level: 'beginner',
        summary: 'Learn the first three building blocks behind most scalable web systems.',
        analogy: 'A receptionist routes people, a sticky note answers repeated questions quickly, and the filing cabinet stores the official record.',
        explanation: 'A load balancer spreads traffic across servers. A cache stores hot reads close to the application. A database keeps durable source-of-truth data. Most beginner designs become clearer when these roles are separated.',
        diagram: ['Users', 'Load balancer', 'App servers', 'Cache', 'Database'],
        tradeoffs: [
            { optionA: 'Cache reads', optionB: 'Read database every time', decisionRule: 'Cache when reads repeat often and freshness tolerance exists.' },
            { optionA: 'Scale app servers', optionB: 'Scale database first', decisionRule: 'Scale stateless app servers before touching harder database scaling.' },
        ],
        quiz: [
            {
                question: 'Which component usually owns the durable source of truth?',
                options: ['Load balancer', 'Cache', 'Database'],
                correctIndex: 2,
                explanation: 'Caches may be stale or temporary; databases hold durable state.',
            },
        ],
        drill: {
            prompt: 'Sketch a read-heavy product page using these three components.',
            checklist: ['Route request', 'Read cache first', 'Fallback to database', 'Update cache on miss'],
        },
        order: 3,
    },
    {
        slug: 'cap-theorem',
        title: 'CAP and PACELC Theorems',
        category: 'fundamentals',
        level: 'beginner',
        summary: 'Understand constraints of distributed systems under network partitions.',
        analogy: 'If phone lines go down, you must choose between taking orders with potential errors or refusing orders to stay accurate.',
        explanation: 'Under network partitions, a distributed system must choose between Availability (returning a local response) or Consistency (blocking/error). PACELC extends this to explain Latency/Consistency trade-offs during normal operations.',
        diagram: ['Node A', 'Partitioned Link', 'Node B', 'Client Request'],
        tradeoffs: [
            { optionA: 'AP (Availability / Partition)', optionB: 'CP (Consistency / Partition)', decisionRule: 'Choose AP when high uptime is required and stale data is acceptable. Choose CP when data must be strictly correct (e.g. banking).' },
            { optionA: 'Latency (EL)', optionB: 'Consistency (EC)', decisionRule: 'Choose lower latency over strong consistency when normal operations need fast responses.' },
        ],
        quiz: [
            {
                question: 'What is guaranteed by a CP system during a network partition?',
                options: ['Every non-failing node returns a response', 'The network will never partition', 'All readable nodes return the most recent write or an error'],
                correctIndex: 2,
                explanation: 'CP systems guarantee Consistency under partitions, meaning stale data is blocked.',
            },
        ],
        drill: {
            prompt: 'A bank database chooses CP over AP. Write one sentence explaining why.',
            checklist: ['Explain risk of stale balances', 'State the chosen trade-off'],
        },
        order: 4,
    },
    {
        slug: 'queues-and-async-work',
        title: 'Queues and Async Work',
        category: 'components',
        level: 'intermediate',
        summary: 'Use queues to protect user-facing requests from slow background work.',
        analogy: 'A front desk accepts your form quickly, then a back office processes it in order.',
        explanation: 'Queues decouple producers from workers. They help absorb spikes, retry failed work, and keep request latency low for tasks like emails, thumbnails, notifications, and analytics.',
        diagram: ['API service', 'Message queue', 'Worker pool', 'External service/storage'],
        tradeoffs: [
            { optionA: 'Async queue', optionB: 'Synchronous request', decisionRule: 'Queue work that does not need to finish before responding to the user.' },
            { optionA: 'At-least-once delivery', optionB: 'Exactly-once behavior', decisionRule: 'Design idempotent workers because retries can happen.' },
        ],
        quiz: [
            {
                question: 'Which task is a good queue candidate?',
                options: ['Password validation before login', 'Sending a welcome email', 'Checking required form fields'],
                correctIndex: 1,
                explanation: 'The welcome email can happen after the response, so it can be queued.',
            },
        ],
        drill: {
            prompt: 'Design async image thumbnail generation for uploaded photos.',
            checklist: ['Accept upload quickly', 'Publish job', 'Worker processes image', 'Store result', 'Handle retry'],
        },
        order: 5,
    },
    {
        slug: 'consistent-hashing',
        title: 'Consistent Hashing Rings',
        category: 'components',
        level: 'intermediate',
        summary: 'Scale distributed nodes with minimal key relocation during resizing.',
        analogy: 'Instead of assigning tasks by indexing names, map names and tasks to a circular clock face and assign tasks to the closest person clockwise.',
        explanation: 'Consistent Hashing places both server nodes and key hashes on a circular hash ring. When nodes are added or removed, only a small fraction of keys are relocated.',
        diagram: ['Circular Hash Ring', 'Server Node Hashes', 'Key Hashes', 'Clockwise Mapping'],
        tradeoffs: [
            { optionA: 'Virtual Nodes', optionB: 'Physical Node Mapping', decisionRule: 'Use Virtual Nodes to ensure load is balanced evenly across servers.' },
            { optionA: 'Consistent Hashing', optionB: 'Modulo Hashing', decisionRule: 'Use Consistent Hashing when the node cluster size fluctuates often.' },
        ],
        quiz: [
            {
                question: 'Why is traditional modulo hashing inefficient for scaling caches?',
                options: ['It uses too much memory', 'Resizing the cluster causes almost all keys to relocate', 'It only works with SQL databases'],
                correctIndex: 1,
                explanation: 'Modulo mapping depends on cluster size N; changing N alters the mappings for nearly all keys.',
            },
        ],
        drill: {
            prompt: 'Explain how virtual nodes solve the "hotspot" (uneven distribution) problem.',
            checklist: ['Define Virtual Nodes', 'Describe distribution uniformity', 'Explain how it helps physical servers'],
        },
        order: 6,
    },
    {
        slug: 'sql-nosql-sharding',
        title: 'SQL, NoSQL, and Sharding',
        category: 'tradeoffs',
        level: 'intermediate',
        summary: 'Choose storage based on access pattern, consistency needs, and scale shape.',
        analogy: 'A spreadsheet is great for structured joins; labeled boxes are better when every item has a different shape and must be fetched quickly by key.',
        explanation: 'SQL is strong for relational data, joins, and transactions. NoSQL often favors flexible schema or high-scale key access. Sharding splits data across machines when one database cannot carry the load.',
        diagram: ['Application', 'Router/shard key', 'Shard A', 'Shard B', 'Replica'],
        tradeoffs: [
            { optionA: 'SQL', optionB: 'NoSQL', decisionRule: 'Use SQL when relationships and transactions dominate.' },
            { optionA: 'Shard by user id', optionB: 'Shard by time', decisionRule: 'Choose a shard key that spreads load and matches common queries.' },
        ],
        quiz: [
            {
                question: 'What is the biggest risk of a poor shard key?',
                options: ['Hot partitions', 'More CSS', 'Faster joins'],
                correctIndex: 0,
                explanation: 'A bad shard key can send too much traffic to one shard.',
            },
        ],
        drill: {
            prompt: 'Pick a shard key for a chat app and explain one risk.',
            checklist: ['Identify primary query', 'Choose shard key', 'Discuss hot rooms/users', 'Mention mitigation'],
        },
        order: 7,
    },
    {
        slug: 'api-gateway-microservices',
        title: 'API Gateway and Microservices',
        category: 'tradeoffs',
        level: 'intermediate',
        summary: 'Decompose monolithic systems into independent resilient microservices.',
        analogy: 'A single multi-purpose shop splits into separate boutique stalls, with a single host greeting customers at the entrance.',
        explanation: 'Monoliths bundle all features together. Microservices separate them by domain, using an API Gateway to handle security, cross-cutting routing, and rate limiting.',
        diagram: ['Client Request', 'API Gateway', 'User Service', 'Order Service', 'Shared DB / Local DB'],
        tradeoffs: [
            { optionA: 'Microservices (Independent DBs)', optionB: 'Monolith (Shared Database)', decisionRule: 'Use Microservices for large, fast-scaling engineering groups requiring decoupled deployment schedules.' },
            { optionA: 'Circuit Breaker fallback', optionB: 'Error Propagation', decisionRule: 'Implement circuit breaker fallbacks to prevent single-service latency from crashing the system.' },
        ],
        quiz: [
            {
                question: 'What is the primary role of an API Gateway in microservices?',
                options: ['Perform heavy numerical computation', 'Store direct source-of-truth customer transactions', 'Act as a single entry point to route, authenticate, and rate limit requests'],
                correctIndex: 2,
                explanation: 'The gateway handles entrance tasks like routing, auth, and rate limiting.',
            },
        ],
        drill: {
            prompt: 'What happens to user requests when a microservices circuit breaker transitions to the "Open" state?',
            checklist: ['Define Open State', 'Mention immediate fail-fast response', 'Explain prevention of downstream load'],
        },
        order: 8,
    },
    {
        slug: 'design-url-shortener',
        title: 'Case Study: URL Shortener',
        category: 'case_studies',
        level: 'interview',
        summary: 'Practice a full beginner-friendly system design prompt with clear tradeoffs.',
        analogy: 'A cloakroom gives a tiny token for a large bag and later retrieves the bag using that token.',
        explanation: 'A URL shortener maps a short code to a long URL. The core design covers code generation, redirect latency, storage, cache, analytics, and abuse controls.',
        diagram: ['Client', 'API service', 'Code generator', 'Database', 'Cache', 'Analytics queue'],
        tradeoffs: [
            { optionA: 'Random code', optionB: 'Counter-based code', decisionRule: 'Use random codes for simpler distributed generation; handle collisions.' },
            { optionA: 'Cache redirects', optionB: 'Always read database', decisionRule: 'Cache hot short codes because redirects are read-heavy.' },
        ],
        quiz: [
            {
                question: 'Why is cache useful in a URL shortener?',
                options: ['Redirects are read-heavy', 'It replaces the database permanently', 'It generates CSS'],
                correctIndex: 0,
                explanation: 'Popular short links may be read many times, so cache reduces latency and database load.',
            },
        ],
        drill: {
            prompt: 'Design a URL shortener for 100M links and read-heavy redirects.',
            checklist: ['Functional requirements', 'QPS estimate', 'Short code strategy', 'Storage', 'Cache', 'Analytics'],
        },
        order: 9,
    },
    {
        slug: 'case-study-video-streaming',
        title: 'Case Study: Video Streaming (YouTube)',
        category: 'case_studies',
        level: 'interview',
        summary: 'Design a scalable platform to ingest, transcode, and stream high-quality videos.',
        analogy: 'A movie studio cuts a film into tiny reels, stores copies in local theaters, and plays the standard or high-def reel depending on screen size.',
        explanation: 'Video systems must accept massive files, partition them into transcoded chunks of varying qualities (HLS/DASH), cache chunks on CDN edges, and support adaptive bitrate playback.',
        diagram: ['Uploader', 'Transcoder Queue', 'Object Storage', 'CDN Edge', 'Client player'],
        tradeoffs: [
            { optionA: 'Client-side Adaptive Bitrate', optionB: 'Fixed Resolution Streaming', decisionRule: 'Use Adaptive Bitrate to prevent video buffering on fluctuating mobile networks.' },
            { optionA: 'Asynchronous Transcoding', optionB: 'Synchronous Video Ingestion', decisionRule: 'Always transcode asynchronously in queues to decouple upload completion from client UI.' },
        ],
        quiz: [
            {
                question: 'Why are videos split into small 2-to-5 second chunks for storage?',
                options: ['To allow parallel transcoding and adaptive quality switching', 'Because object databases cannot store large files', 'To improve CSS styling performance'],
                correctIndex: 0,
                explanation: 'Small chunks enable the client to swap qualities mid-stream and let transcoders encode parts concurrently.',
            },
        ],
        drill: {
            prompt: 'Design the write path for a video uploader system.',
            checklist: ['Raw video upload', 'Asynchronous job queue', 'Transcoding worker pool', 'Storage of manifests'],
        },
        order: 10,
    },
    {
        slug: 'case-study-uber',
        title: 'Case Study: Ride-Hailing (Uber)',
        category: 'case_studies',
        level: 'interview',
        summary: 'Design a system that tracks drivers and matches them with nearby riders in real-time.',
        analogy: 'Dividing a city map into numbered hexagonal blocks so dispatchers only search the caller’s local block and surrounding neighbors.',
        explanation: 'Ride hailing requires processing high-throughput GPS streams via WebSockets, mapping driver locations to a geo-spatial index (Geohash or H3), and running fast matching queries.',
        diagram: ['Driver WebSocket', 'Geo-index (Redis)', 'Match Engine', 'Rider App'],
        tradeoffs: [
            { optionA: 'In-memory geo-index (Redis/Memcached)', optionB: 'Disk database 2D index', decisionRule: 'Use in-memory spatial indexes for driver coordinates updating every 4 seconds.' },
            { optionA: 'Client WebSockets', optionB: 'Client HTTP Polling', decisionRule: 'Use WebSockets when real-time moving markers are critical to rider experience.' },
        ],
        quiz: [
            {
                question: 'What is the purpose of Geo-spatial indexing algorithms like Geohash or H3?',
                options: ['To compile Javascript code faster', 'To group Earth coordinates into searchable grid-based blocks for rapid spatial queries', 'To encrypt driver user profiles'],
                correctIndex: 1,
                explanation: 'Geo-indexes map 2D coordinates to 1D strings or cells, speeding up nearby-driver queries.',
            },
        ],
        drill: {
            prompt: 'Design real-time driver tracking for 100K active drivers.',
            checklist: ['Driver location payload size', 'QPS calculations', 'WebSocket Gateway', 'In-memory coordinate cache'],
        },
        order: 11,
    },
]

export const systemDesignPromptSeeds = [
    {
        slug: 'url-shortener',
        title: 'Design a URL Shortener',
        difficulty: 'Easy',
        scenario: 'Design a service that creates short links and redirects users to long URLs with low latency.',
        requirements: ['Create short URL', 'Redirect short URL', 'Track basic click analytics', 'Handle custom aliases optionally'],
        scaleAssumptions: ['100M stored URLs', 'Read-heavy traffic', 'Popular links can spike'],
        expectedComponents: ['API service', 'Code generator', 'Database', 'Cache', 'Analytics queue'],
        tradeoffFocus: ['Code generation strategy', 'Cache freshness', 'Collision handling'],
        followUps: ['How do you prevent abuse?', 'How do you expire links?', 'How do you support custom aliases?'],
        order: 1,
    },
    {
        slug: 'chat-app',
        title: 'Design a Chat App',
        difficulty: 'Medium',
        scenario: 'Design one-to-one and small-group messaging with online delivery and message history.',
        requirements: ['Send messages', 'Receive messages in near real time', 'Store history', 'Show delivery status'],
        scaleAssumptions: ['Millions of users', 'Many idle connections', 'Messages must be durable'],
        expectedComponents: ['Gateway/WebSocket service', 'Message service', 'Queue', 'Database', 'Presence store'],
        tradeoffFocus: ['WebSocket vs polling', 'Ordering', 'Offline delivery'],
        followUps: ['How do you handle huge groups?', 'How do you support search?', 'How do you retry failed sends?'],
        order: 2,
    },
    {
        slug: 'rate-limiter',
        title: 'Design a Rate Limiter',
        difficulty: 'Medium',
        scenario: 'Design a service that limits requests per user or API key to protect backend systems.',
        requirements: ['Enforce request limits', 'Return retry guidance', 'Support distributed servers'],
        scaleAssumptions: ['High QPS', 'Multiple regions optional', 'Low latency decision needed'],
        expectedComponents: ['API gateway', 'Counter store', 'Rules config', 'Metrics'],
        tradeoffFocus: ['Token bucket vs fixed window', 'Redis counters', 'Consistency under distribution'],
        followUps: ['How do you avoid hot keys?', 'How do you handle burst traffic?', 'How do you test correctness?'],
        order: 3,
    },
    {
        slug: 'notification-service',
        title: 'Design a Notification Service',
        difficulty: 'Medium',
        scenario: 'Design a scalable notification engine sending bulk and transactional SMS, Email, and Push alerts.',
        requirements: ['Support multiple notification channels (SMS, email, push)', 'Handle prioritize messaging queues', 'Ensure low latency delivery', 'Implement provider fallbacks and retries'],
        scaleAssumptions: ['10M alerts per day', 'Spiky traffic during flash sales', 'Varying third-party API rates'],
        expectedComponents: ['API Gateway', 'Priority Queue (RabbitMQ/Kafka)', 'Worker Pool', 'Template Engine', 'User Profile Cache', 'Retry / Dead Letter Queue'],
        tradeoffFocus: ['Asynchronous event routing', 'Deduplication strategies', 'Idempotent worker design'],
        followUps: ['How do you prevent duplicate alerts?', 'How does the system handle a complete email provider outage?', 'How do users manage alert settings?'],
        order: 4,
    },
    {
        slug: 'video-streaming',
        title: 'Design a Video Streaming Platform (YouTube)',
        difficulty: 'Hard',
        scenario: 'Design a global video platform accepting creator uploads, transcoding them, and serving adaptive playback streams.',
        requirements: ['Upload videos', 'Support adaptive bitrate video streaming', 'Search catalog and view metadata', 'Track views and engagement metrics'],
        scaleAssumptions: ['500 hours uploaded per minute', '1 Billion daily active views', 'Petabytes of storage required'],
        expectedComponents: ['Ingestion Server', 'Transcoding Queue', 'Object Storage (S3)', 'CDN Edges', 'API Metadata Server', 'User Action Event Queue'],
        tradeoffFocus: ['Video chunking size', 'HLS vs DASH protocols', 'CDN cache eviction policies'],
        followUps: ['How do you scale transcoding clusters?', 'How do you optimize cost for cold videos?', 'How do you handle copyright infringement scanning?'],
        order: 5,
    },
    {
        slug: 'uber',
        title: 'Design a Ride-Hailing Platform (Uber)',
        difficulty: 'Hard',
        scenario: 'Design a real-time system coordinating taxi matching, pricing, driver tracking, and maps routing.',
        requirements: ['Track driver location in real time', 'Match riders with nearby drivers', 'Calculate trip ETAs and dynamic pricing', 'Track trip routes on active rides'],
        scaleAssumptions: ['1M active drivers', '10M daily trips', 'High QPS coordinate updates'],
        expectedComponents: ['WebSocket Gateway', 'Geo-Index Store (Redis)', 'Match Engine', 'Trip Metadata database (Cassandra)', 'Map/ETA Calculator'],
        tradeoffFocus: ['Geo-spatial indices (H3 vs Geohash)', 'WebSocket state management', 'Locking mechanisms during driver assignment'],
        followUps: ['How do you handle matching in highly dense areas (hotspots)?', 'How does dynamic surge pricing calculate demand?', 'How do you recover state when a WebSocket server crashes?'],
        order: 6,
    },
    {
        slug: 'web-crawler',
        title: 'Design a Distributed Web Crawler',
        difficulty: 'Hard',
        scenario: 'Design a system that crawls the entire World Wide Web, indexes content, and updates page metadata.',
        requirements: ['Traverse web pages starting from seed URLs', 'Extract content, links, and documents', 'Observe politeness policies (robots.txt)', 'Detect and ignore duplicate pages'],
        scaleAssumptions: ['10 Billion pages crawled', 'Highly distributed network', 'Massive storage needs'],
        expectedComponents: ['URL Frontier', 'DNS Resolver cache', 'Fetch workers', 'HTML Parser', 'Deduplication filter (Bloom Filter)', 'Storage (Bigtable)'],
        tradeoffFocus: ['Frontier prioritization', 'Politeness enforcement queues', 'Content signature hashing'],
        followUps: ['How do you crawl JavaScript-heavy single-page apps?', 'How do you prevent falling into crawler traps (infinite loops)?', 'How do you update the crawled status of web pages dynamically?'],
        order: 7,
    },
]
